//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvzon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>svt1.svt.se</string>\r\n  <string>svt1hd.svt.se</string>\r\n  <string>svt2.svt" +
            ".se</string>\r\n  <string>svt2hd.svt.se</string>\r\n  <string>tv3.se</string>\r\n  <st" +
            "ring>hd.tv3.se</string>\r\n  <string>tv4.se</string>\r\n  <string>hd.tv4.se</string>" +
            "\r\n  <string>fakta.tv4.se</string>\r\n  <string>film.tv4.se</string>\r\n  <string>spo" +
            "rt.tv4.se</string>\r\n  <string>tv12.tv4.se</string>\r\n  <string>kanal5.se</string>" +
            "\r\n  <string>hd.kanal5.se</string>\r\n  <string>tv6.se</string>\r\n  <string>tnt-tv.s" +
            "e</string>\r\n  <string>sjuan.se</string>\r\n  <string>tv11.sbstv.se</string>\r\n  <st" +
            "ring>tv8.se</string>\r\n  <string>kanal9.se</string>\r\n  <string>tv10.se</string>\r\n" +
            "  <string>axess.se</string>\r\n  <string>showtime.nonstop.tv</string>\r\n  <string>s" +
            "ilver.nonstop.tv</string>\r\n  <string>tcmeurope.com</string>\r\n  <string>eurosport" +
            ".se</string>\r\n  <string>eurosport2.se</string>\r\n  <string>kanalglobal.se</string" +
            ">\r\n  <string>animalplanet.se</string>\r\n  <string>discoverychannel.se</string>\r\n " +
            " <string>science.discoverychannel.com</string>\r\n  <string>tlcsverige.se</string>" +
            "\r\n  <string>hd.natgeo.se</string>\r\n  <string>cartoonnetwork.se</string>\r\n  <stri" +
            "ng>disneychannel.se</string>\r\n  <string>xd.disneychannel.se</string>\r\n  <string>" +
            "bbcworldnews.com</string>\r\n  <string>nickelodeon.se</string>\r\n  <string>comedyce" +
            "ntral.tv</string>\r\n  <string>mtv.se</string>\r\n  <string>hd.mtv.se</string>\r\n  <s" +
            "tring>star.nonstop.tv</string>\r\n  <string>vh1.se</string>\r\n  <string>cnn.com</st" +
            "ring>\r\n  <string>kunskapskanalen.svt.se</string>\r\n  <string>svtb-svt24.svt.se</s" +
            "tring>\r\n  <string>travelchanneltv.se</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Channels {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Channels"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ProgramData\\DVBLogic\\DVBLink\\xmltv\\tvzon.xml")]
        public string OutputPath {
            get {
                return ((string)(this["OutputPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int Days {
            get {
                return ((int)(this["Days"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SerializableStringDictionary ImageCache {
            get {
                return ((global::SerializableStringDictionary)(this["ImageCache"]));
            }
            set {
                this["ImageCache"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int DaysInHistory {
            get {
                return ((int)(this["DaysInHistory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WriteToLog {
            get {
                return ((bool)(this["WriteToLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int PreviousShownDuration {
            get {
                return ((int)(this["PreviousShownDuration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InsertEpisodeInDesc {
            get {
                return ((bool)(this["InsertEpisodeInDesc"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xxxxxxxx")]
        public string apiKey {
            get {
                return ((string)(this["apiKey"]));
            }
            set {
                this["apiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xxxxxxxxxx")]
        public string apiSecret {
            get {
                return ((string)(this["apiSecret"]));
            }
            set {
                this["apiSecret"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<SerializableStringDictionary>\r\n  <Array" +
            "OfAnyType xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http:" +
            "//www.w3.org/2001/XMLSchema\">\r\n    <anyType xsi:type=\"Node\">\r\n      <key>tnt-tv." +
            "se</key>\r\n      <val>tv7</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n " +
            "     <key>kanal5.se</key>\r\n      <val>kanal5</val>\r\n    </anyType>\r\n    <anyType" +
            " xsi:type=\"Node\">\r\n      <key>star.nonstop.tv</key>\r\n      <val>star!</val>\r\n   " +
            " </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>kunskapskanalen.svt.se</k" +
            "ey>\r\n      <val>kunskapskanalen</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"No" +
            "de\">\r\n      <key>kanalglobal.se</key>\r\n      <val>kanalglobal</val>\r\n    </anyTy" +
            "pe>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>silver.nonstop.tv</key>\r\n      <v" +
            "al>silver</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>svtb-" +
            "svt24.svt.se</key>\r\n      <val>barnkanalen</val>\r\n    </anyType>\r\n    <anyType x" +
            "si:type=\"Node\">\r\n      <key>nickelodeon.se</key>\r\n      <val>nickelodeon</val>\r\n" +
            "    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>svt1.svt.se</key>\r\n   " +
            "   <val>svt1</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>di" +
            "sneychannel.se</key>\r\n      <val>disneychannel</val>\r\n    </anyType>\r\n    <anyTy" +
            "pe xsi:type=\"Node\">\r\n      <key>kanal9.se</key>\r\n      <val>kanal9</val>\r\n    </" +
            "anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>tv10.se</key>\r\n      <val>tv" +
            "10</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>showtime.non" +
            "stop.tv</key>\r\n      <val>showtime</val>\r\n    </anyType>\r\n    <anyType xsi:type=" +
            "\"Node\">\r\n      <key>tv6.se</key>\r\n      <val>tv6</val>\r\n    </anyType>\r\n    <any" +
            "Type xsi:type=\"Node\">\r\n      <key>tv8.se</key>\r\n      <val>tv8</val>\r\n    </anyT" +
            "ype>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>film.tv4.se</key>\r\n      <val>tv" +
            "4film</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>cartoonne" +
            "twork.se</key>\r\n      <val>cartoonnetwork</val>\r\n    </anyType>\r\n    <anyType xs" +
            "i:type=\"Node\">\r\n      <key>hd.mtv.se</key>\r\n      <val>mtvn-hd</val>\r\n    </anyT" +
            "ype>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>sjuan.se</key>\r\n      <val>sjuan" +
            "</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>hd.tv4.se</key" +
            ">\r\n      <val>tv4hd</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      " +
            "<key>tv11.tv4.se</key>\r\n      <val>tv11</val>\r\n    </anyType>\r\n    <anyType xsi:" +
            "type=\"Node\">\r\n      <key>svt1hd.svt.se</key>\r\n      <val>svt1hd</val>\r\n    </any" +
            "Type>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>science.discoverychannel.com</k" +
            "ey>\r\n      <val>discoveryscience</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"N" +
            "ode\">\r\n      <key>xd.disneychannel.se</key>\r\n      <val>disneyxd</val>\r\n    </an" +
            "yType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>animalplanet.se</key>\r\n      <" +
            "val>animalplanet</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <ke" +
            "y>discoverychannel.se</key>\r\n      <val>discovery</val>\r\n    </anyType>\r\n    <an" +
            "yType xsi:type=\"Node\">\r\n      <key>travelchanneltv.se</key>\r\n      <val>travel</" +
            "val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>tcmeurope.com</k" +
            "ey>\r\n      <val>tcm</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      " +
            "<key>bbcworldnews.com</key>\r\n      <val>bbcworld</val>\r\n    </anyType>\r\n    <any" +
            "Type xsi:type=\"Node\">\r\n      <key>mtv.se</key>\r\n      <val>mtv</val>\r\n    </anyT" +
            "ype>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>sport.tv4.se</key>\r\n      <val>t" +
            "v4sport</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>axess.s" +
            "e</key>\r\n      <val>axesstv</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">" +
            "\r\n      <key>eurosport2.se</key>\r\n      <val>eurosport2</val>\r\n    </anyType>\r\n " +
            "   <anyType xsi:type=\"Node\">\r\n      <key>cnn.com</key>\r\n      <val>cnn</val>\r\n  " +
            "  </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>hd.tv3.se</key>\r\n      <" +
            "val>tv3hd</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>euros" +
            "port.se</key>\r\n      <val>eurosport</val>\r\n    </anyType>\r\n    <anyType xsi:type" +
            "=\"Node\">\r\n      <key>hd.kanal5.se</key>\r\n      <val>kanal5hd</val>\r\n    </anyTyp" +
            "e>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>svt2.svt.se</key>\r\n      <val>svt2" +
            "</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>svt2hd.svt.se<" +
            "/key>\r\n      <val>svt2hd</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n " +
            "     <key>tlcsverige.se</key>\r\n      <val>tlc</val>\r\n    </anyType>\r\n    <anyTyp" +
            "e xsi:type=\"Node\">\r\n      <key>tv3.se</key>\r\n      <val>tv3</val>\r\n    </anyType" +
            ">\r\n    <anyType xsi:type=\"Node\">\r\n      <key>tv4.se</key>\r\n      <val>tv4</val>\r" +
            "\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>hd.natgeo.se</key>\r\n " +
            "     <val>nationalgeographichd</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Nod" +
            "e\">\r\n      <key>fakta.tv4.se</key>\r\n      <val>tv4fakta</val>\r\n    </anyType>\r\n " +
            "   <anyType xsi:type=\"Node\">\r\n      <key>comedycentral.tv</key>\r\n      <val>come" +
            "dycentral</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"Node\">\r\n      <key>news." +
            "tv4.se</key>\r\n      <val>tv4news</val>\r\n    </anyType>\r\n    <anyType xsi:type=\"N" +
            "ode\">\r\n      <key>vh1.se</key>\r\n      <val>vh1</val>\r\n    </anyType>\r\n  </ArrayO" +
            "fAnyType>\r\n</SerializableStringDictionary>")]
        public global::SerializableStringDictionary TvNuMappings {
            get {
                return ((global::SerializableStringDictionary)(this["TvNuMappings"]));
            }
        }
    }
}
